"""Example questions on the welcome screen.

Personal ones are generated by the user's chosen model from their recent chat titles
(cached; regenerated about twice a day or after a few new chats), with a seasonal pool as
the fallback for new users, while generating, or when generation fails.
"""
import json
import random
import re
import subprocess
import threading
import time

from . import agent, paths, settings

CACHE = paths.DATA_DIR / "suggestions.json"
MAX_AGE = 12 * 3600
NEW_CHATS = 3        # regenerate after this many new chats
MIN_CHATS = 3        # personalise only once there's some history

POOL = [
    "想买一台扫地机器人，现在大家最推荐哪款？有什么坑？",
    "第一次养猫需要准备什么？大家都后悔买了什么？",
    "上海适合一个人周末去的小众展览或咖啡店",
    "油皮夏天用什么防晒不闷痘？",
    "租房第一次签合同要注意哪些坑？",
    "新手健身一周练几次比较合适？",
    "30 岁左右适合的通勤包有哪些推荐？",
    "空气炸锅真的好用吗？哪些功能是智商税？",
    "带 3 岁孩子去日本玩，哪些地方适合？",
    "新手入门咖啡，第一台磨豆机买什么？",
    "考研二战值得吗？过来人都怎么说？",
    "装修时哪些钱最不该省？",
    "敏感肌换季怎么护肤？",
    "第一次去香港玩要注意什么？",
    "适合送父母的实用礼物有哪些？",
    "北京周末适合带老人去的地方",
    "办公室久坐腰疼，大家都怎么缓解？",
    "新车买哪种车险组合比较划算？",
    "露营新手需要买哪些装备？哪些可以不买？",
    "有哪些适合一个人吃的快手晚餐？",
]
SEASONAL = {  # month -> ideas
    1: ["春节回家带什么伴手礼比较体面？", "寒假带孩子去哪里玩人少？"],
    2: ["春节后怎么快速调整作息？", "开春适合去哪里看花？"],
    3: ["春天适合去哪里赏花人少？", "换季过敏大家都怎么缓解？"],
    4: ["五一假期去哪里玩人少景美？", "春季踏青野餐需要准备什么？"],
    5: ["五一出游有哪些避坑提醒？", "夏天防晒霜怎么选？"],
    6: ["618 哪些东西真的值得买？", "毕业旅行去哪里性价比高？"],
    7: ["暑假带孩子去哪里玩比较好？", "夏天去哪里避暑人少？"],
    8: ["开学季学生党需要准备什么？", "夏天吃什么不容易胖？"],
    9: ["国庆出游去哪里人少景美？", "秋天适合去哪里看红叶？"],
    10: ["双 11 哪些东西真的值得囤？", "秋冬换季护肤要注意什么？"],
    11: ["双 11 之后退货有哪些坑？", "冬天去哪里旅游比较暖和？"],
    12: ["圣诞节约会去哪里比较有氛围？", "跨年去哪里玩人少？"],
}

_lock = threading.Lock()
_busy = {"on": False}


def _fallback(n=4, exclude=()):
    ideas = [q for q in SEASONAL.get(int(time.strftime("%m")), []) + POOL if q not in exclude]
    seasonal = [q for q in SEASONAL.get(int(time.strftime("%m")), []) if q not in exclude][:1]
    rest = [q for q in ideas if q not in seasonal]
    return seasonal + random.sample(rest, max(0, min(n - len(seasonal), len(rest))))


def _read():
    try:
        return json.loads(CACHE.read_text())
    except (FileNotFoundError, ValueError):
        return {}


def get(exclude=()):
    """Four suggestions (personal when available) and whether they're personal."""
    chats = agent.list_chats()
    cache = _read()
    stale = (time.time() - cache.get("at", 0) > MAX_AGE) or (len(chats) - cache.get("chats", 0) >= NEW_CHATS)
    if len(chats) >= MIN_CHATS and stale and settings.notice_accepted():
        refresh_later(chats)
    personal = [q for q in cache.get("items", []) if q not in exclude]
    if len(personal) >= 4:
        random.shuffle(personal)
        return {"items": personal[:4], "personal": True}
    return {"items": personal + _fallback(4 - len(personal), exclude=set(exclude) | set(personal)),
            "personal": bool(personal)}


def refresh_later(chats):
    with _lock:
        if _busy["on"]:
            return
        _busy["on"] = True

    def run():
        try:
            items = _generate([c["title"] for c in chats[:25]])
            if items:
                CACHE.write_text(json.dumps({"at": time.time(), "chats": len(chats), "items": items},
                                            ensure_ascii=False))
        except Exception:
            pass
        finally:
            _busy["on"] = False
    threading.Thread(target=run, daemon=True).start()


def _prompt(titles):
    recent = "\n".join(f"- {t}" for t in titles)
    return f"""你在帮一个「小红书调研助手」的首页想示例问题。今天是 {time.strftime("%Y-%m-%d")}。
用户最近问过这些问题（按时间从新到旧）：
{recent}

请根据用户的兴趣，想 8 个他接下来可能想在小红书上调研的新问题：
- 和他关心的领域相关，但不要重复上面已经问过的；可以是更深入的追问、相关的对比，或者同类的新话题；
- 适当结合当前季节和节日；
- 每个问题 12～30 个字，口语化，像真人会问的；
- 不要涉及违法、医疗诊断、投资建议。

只输出一个 JSON 数组，包含 8 个字符串，不要任何其他文字。"""


def _parse(text):
    m = re.search(r"\[[\s\S]*\]", text or "")
    if not m:
        return []
    try:
        items = json.loads(m.group(0))
    except ValueError:
        return []
    return [str(x).strip()[:60] for x in items if isinstance(x, str) and 4 <= len(x.strip()) <= 60][:8]


def _generate(titles):
    conf = settings.load()
    prompt = _prompt(titles)
    backend = conf["backend"]
    if backend == "api":
        if not settings.api_ready(conf):
            return []
        from . import llm
        cl, model = llm.client(conf)
        r = cl.chat.completions.create(model=model, messages=[{"role": "user", "content": prompt}])
        return _parse(r.choices[0].message.content)
    env = paths.child_env()
    env.pop("CLAUDECODE", None)
    if backend == "codex":
        codex = settings.find_codex()
        if not codex:
            return []
        out = paths.DATA_DIR / "suggestions.codex.txt"
        subprocess.run([codex, "exec", "--skip-git-repo-check", "--ignore-user-config",
                        "-c", 'sandbox_mode="read-only"', "-c", 'approval_policy="never"', "-c", 'web_search="disabled"',
                        "-o", str(out), prompt], cwd=paths.DATA_DIR, env=env, capture_output=True, timeout=180)
        try:
            return _parse(out.read_text())
        finally:
            out.unlink(missing_ok=True)
    claude = settings.find_claude()
    if not claude:
        return []
    # A small, cheap call: no tools, not saved as a session, the lighter model unless chosen otherwise.
    r = subprocess.run([claude, "-p", "--output-format", "text", "--no-session-persistence",
                        "--model", conf.get("claude_model") or "sonnet", "--tools", ""],
                       input=prompt, cwd=paths.DATA_DIR, env=env, capture_output=True, text=True, timeout=180)
    return _parse(r.stdout)
